server:
  port: 11011
  servlet:
    context-path: /api/v1

spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
#     Redis服务器连接密码（默认为空）
#    password: 123456